export const restaurants = [
  {
    id: 1,
    image: "images/restaurants/img1.jpg",
    title: "Fatafeat",
    description:
      "Check out menus from popular local restaurants and chains. Order something new or tuck into your favorite go-to.",
    link: "/restaurant/fatafeat",
    alias: "fatafeat",
    openAt: "2023-03-24T15:30:44.598Z",
    lat: 34.8982922,
    lng: 35.8760316,
    meals: [
      {
        id: 1,
        title: "Tax-Max Pizza",
        description: "Chicken, onions, green peppers, black olives.",
        cost: "42000",
        restaurant: "Fatafeat",
      },
      {
        id: 2,
        title: "Dynamite Pizza",
        description: "Chicken breast, dynamite sauce.",
        cost: "48000",
        restaurant: "Fatafeat",
      },
      {
        id: 3,
        title: "Deluxe Feast Pizza",
        description: "Pepperoni, Italian sujuk, mushroom, onion, green pepper.",
        cost: "30000",
        restaurant: "Fatafeat",
      },
      {
        id: 4,
        title: "Hot & Spicy Pizza",
        description: "Beef, onion, green pepper and hot pepper.",
        cost: "50000",
        restaurant: "Fatafeat",
      },
      {
        id: 5,
        title: "Caprese Pizza",
        description: "Chicken, tomatoes, pesto sauce.",
        cost: "43000",
        restaurant: "Fatafeat",
      },
      {
        id: 6,
        title: "Hawana Pizza",
        description: "Pepperoni, pineapple.",
        cost: "35000",
        restaurant: "Fatafeat",
      },
      {
        id: 7,
        title: "Mix Cheese Pizza",
        description: "Parmesan, feta, kashkaval, edam.",
        cost: "45000",
        restaurant: "Fatafeat",
      },
    ],
  },
  {
    id: 2,
    image: "images/restaurants/img2.webp",
    title: "Al Aseel",
    description:
      "Donate your change at checkout to the Restaurant Strong Fund to support local restaurants that have been impacted by the pandemic.",
    link: "/restaurant/al-aseel",
    alias: "al-aseel",
    openAt: "2023-03-24T12:30:44.598Z",
    lat: 34.8789653,
    lng: 35.9003917,
    meals: [
      {
        id: 1,
        title: "Tax-Max Pizza",
        description: "Chicken, onions, green peppers, black olives.",
        cost: "42000",
        restaurant: "Al Aseel",
      },
      {
        id: 2,
        title: "Dynamite Pizza",
        description: "Chicken breast, dynamite sauce.",
        cost: "48000",
        restaurant: "Al Aseel",
      },
      {
        id: 3,
        title: "Deluxe Feast Pizza",
        description: "Pepperoni, Italian sujuk, mushroom, onion, green pepper.",
        cost: "30000",
        restaurant: "Al Aseel",
      },
      {
        id: 4,
        title: "Hot & Spicy Pizza",
        description: "Beef, onion, green pepper and hot pepper.",
        cost: "50000",
        restaurant: "Al Aseel",
      },
      {
        id: 5,
        title: "Caprese Pizza",
        description: "Chicken, tomatoes, pesto sauce.",
        cost: "43000",
        restaurant: "Al Aseel",
      },
      {
        id: 6,
        title: "Hawana Pizza",
        description: "Pepperoni, pineapple.",
        cost: "35000",
        restaurant: "Al Aseel",
      },
      {
        id: 7,
        title: "Mix Cheese Pizza",
        description: "Parmesan, feta, kashkaval, edam.",
        cost: "45000",
        restaurant: "Al Aseel",
      },
    ],
  },
  {
    id: 3,
    image: "images/restaurants/img3.png",
    title: "Big Bite",
    description:
      "Kick back and enjoy exclusive deals and rewards. Discover new restaurants and get $100s in savings with Perks.",
    link: "/restaurant/big-bite",
    alias: "big-bite",
    openAt: "2023-03-24T14:30:44.598Z",
    lat: 34.8345121,
    lng: 35.9056142,
    meals: [
      {
        id: 1,
        title: "Tax-Max Pizza",
        description: "Chicken, onions, green peppers, black olives.",
        cost: "42000",
        restaurant: "Big Bite",
      },
      {
        id: 2,
        title: "Dynamite Pizza",
        description: "Chicken breast, dynamite sauce.",
        cost: "48000",
        restaurant: "Big Bite",
      },
      {
        id: 3,
        title: "Deluxe Feast Pizza",
        description: "Pepperoni, Italian sujuk, mushroom, onion, green pepper.",
        cost: "30000",
        restaurant: "Big Bite",
      },
      {
        id: 4,
        title: "Hot & Spicy Pizza",
        description: "Beef, onion, green pepper and hot pepper.",
        cost: "50000",
        restaurant: "Big Bite",
      },
      {
        id: 5,
        title: "Caprese Pizza",
        description: "Chicken, tomatoes, pesto sauce.",
        cost: "43000",
        restaurant: "Big Bite",
      },
      {
        id: 6,
        title: "Hawana Pizza",
        description: "Pepperoni, pineapple.",
        cost: "35000",
        restaurant: "Big Bite",
      },
      {
        id: 7,
        title: "Mix Cheese Pizza",
        description: "Parmesan, feta, kashkaval, edam.",
        cost: "45000",
        restaurant: "Big Bite",
      },
    ],
  },
  {
    id: 4,
    image: "images/restaurants/food3.jpg",
    title: "Chef man",
    description:
      "Check out menus from popular local restaurants and chains. Order something new or tuck into your favorite go-to.",
    link: "/restaurant/chef-man",
    alias: "chef-man",
    openAt: "2023-03-24T07:30:44.598Z",
    lat: 34.8915096,
    lng: 35.8930515,
    meals: [
      {
        id: 1,
        title: "Tax-Max Pizza",
        description: "Chicken, onions, green peppers, black olives.",
        cost: "42000",
        restaurant: "Chef man",
      },
      {
        id: 2,
        title: "Dynamite Pizza",
        description: "Chicken breast, dynamite sauce.",
        cost: "48000",
        restaurant: "Chef man",
      },
      {
        id: 3,
        title: "Deluxe Feast Pizza",
        description: "Pepperoni, Italian sujuk, mushroom, onion, green pepper.",
        cost: "30000",
        restaurant: "Chef man",
      },
      {
        id: 4,
        title: "Hot & Spicy Pizza",
        description: "Beef, onion, green pepper and hot pepper.",
        cost: "50000",
        restaurant: "Chef man",
      },
      {
        id: 5,
        title: "Caprese Pizza",
        description: "Chicken, tomatoes, pesto sauce.",
        cost: "43000",
        restaurant: "Chef man",
      },
      {
        id: 6,
        title: "Hawana Pizza",
        description: "Pepperoni, pineapple.",
        cost: "35000",
        restaurant: "Chef man",
      },
      {
        id: 7,
        title: "Mix Cheese Pizza",
        description: "Parmesan, feta, kashkaval, edam.",
        cost: "45000",
        restaurant: "Chef man",
      },
    ],
  },
  {
    id: 5,
    image: "images/restaurants/food4.jpg",
    title: "Happy Meal",
    description:
      "Donate your change at checkout to the Restaurant Strong Fund to support local restaurants that have been impacted by the pandemic.",
    link: "/restaurant/happy-meal",
    alias: "happy-meal",
    openAt: "2023-03-24T14:30:44.598Z",
    lat: 34.8854913,
    lng: 35.8785918,
    meals: [
      {
        id: 1,
        title: "Tax-Max Pizza",
        description: "Chicken, onions, green peppers, black olives.",
        cost: "42000",
        restaurant: "Happy Meal",
      },
      {
        id: 2,
        title: "Dynamite Pizza",
        description: "Chicken breast, dynamite sauce.",
        cost: "48000",
        restaurant: "Happy Meal",
      },
      {
        id: 3,
        title: "Deluxe Feast Pizza",
        description: "Pepperoni, Italian sujuk, mushroom, onion, green pepper.",
        cost: "30000",
        restaurant: "Happy Meal",
      },
      {
        id: 4,
        title: "Hot & Spicy Pizza",
        description: "Beef, onion, green pepper and hot pepper.",
        cost: "50000",
        restaurant: "Happy Meal",
      },
      {
        id: 5,
        title: "Caprese Pizza",
        description: "Chicken, tomatoes, pesto sauce.",
        cost: "43000",
        restaurant: "Happy Meal",
      },
      {
        id: 6,
        title: "Hawana Pizza",
        description: "Pepperoni, pineapple.",
        cost: "35000",
        restaurant: "Happy Meal",
      },
      {
        id: 7,
        title: "Mix Cheese Pizza",
        description: "Parmesan, feta, kashkaval, edam.",
        cost: "45000",
        restaurant: "Happy Meal",
      },
    ],
  },
  {
    id: 6,
    image: "images/restaurants/food5.jpg",
    title: "Masaya",
    description:
      "Kick back and enjoy exclusive deals and rewards. Discover new restaurants and get $100s in savings with Perks.",
    link: "/restaurant/masaya",
    alias: "masaya",
    openAt: "2023-03-24T11:30:44.598Z",
    lat: 34.8830713,
    lng: 35.885101,
    meals: [
      {
        id: 1,
        title: "Tax-Max Pizza",
        description: "Chicken, onions, green peppers, black olives.",
        cost: "42000",
        restaurant: "Masaya",
      },
      {
        id: 2,
        title: "Dynamite Pizza",
        description: "Chicken breast, dynamite sauce.",
        cost: "48000",
        restaurant: "Masaya",
      },
      {
        id: 3,
        title: "Deluxe Feast Pizza",
        description: "Pepperoni, Italian sujuk, mushroom, onion, green pepper.",
        cost: "30000",
        restaurant: "Masaya",
      },
      {
        id: 4,
        title: "Hot & Spicy Pizza",
        description: "Beef, onion, green pepper and hot pepper.",
        cost: "50000",
        restaurant: "Masaya",
      },
      {
        id: 5,
        title: "Caprese Pizza",
        description: "Chicken, tomatoes, pesto sauce.",
        cost: "43000",
        restaurant: "Masaya",
      },
      {
        id: 6,
        title: "Hawana Pizza",
        description: "Pepperoni, pineapple.",
        cost: "35000",
        restaurant: "Masaya",
      },
      {
        id: 7,
        title: "Mix Cheese Pizza",
        description: "Parmesan, feta, kashkaval, edam.",
        cost: "45000",
        restaurant: "Masaya",
      },
    ],
  },
];

export const users = [
  {
    id: 1,
    email: "lamahasan1996@gmail.com",
    password: "lamahasan",
    name: "Lama Hasan",
    type: "user",
  },
  {
    id: 2,
    email: "admin@gmail.com",
    password: "P@ssw0rd_",
    name: "Alaa Ahmad",
    type: "admin",
  },
];
